### ISSUE TITLE
我使用了最新的typecho，文章里面的评论框没有显示

### ISSUE THREAD

**Issue by seekdoor** [zgq354/typecho-theme-next#10]
版本：1.1 (17.10.30)
网址：[https://www.zhuanfanqian.net/](https://www.zhuanfanqian.net/)
环境是lnmp

**Comment by seekdoor** [comment]
![Snipaste_2018-07-21_21-00-53.jpg](https://i.loli.net/2018/07/21/5b532f60c6645.jpg)

我的之前的旧版本的是可以用的，[http://blog.pcwuyu.com](http://blog.pcwuyu.com)

**Comment by zgq354** [comment]
可能是没启用评论？我的最新开发版一切正常
