### ISSUE TITLE
主题里更换头像以后，还是原头像,，如何操作？

### ISSUE THREAD

**Issue by ghost** [zgq354/typecho-theme-next#11]
https://cdn.v2ex.com/gravatar/91dc4d2e4d93b42f4a10c1d8fe632635?s=160&d=mm&r=g
https://cdn.v2ex.com/gravatar/91dc4d2e4d93b42f4a10c1d8fe632635.png

**Comment by zgq354** [comment]
需要在 gravatar.com 设置头像
