### ISSUE TITLE
能否添加超过多少行就变成阅读全文呢

### ISSUE THREAD

**Issue by KevinZonda** [zgq354/typecho-theme-next#14]
我想要一个类似于原主题一样，超越多少行便自动变成阅读全文那种（不显示完全）

希望作者愿意添加这个功能，谢谢啦！

**Comment by zgq354** [comment]
可以的，但其实最好手动来



---原始邮件---
发件人: "Kevin"<notifications@github.com&gt;
发送时间: 2020年3月6日(周五) 上午10:05
收件人: "zgq354/typecho-theme-next"<typecho-theme-next@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zgq354/typecho-theme-next] 能否添加超过多少行就变成阅读全文呢 (#14)



我想要一个类似于原主题一样，超越多少行便自动变成阅读全文那种（不显示完全）
 
希望作者愿意添加这个功能，谢谢啦！

**Comment by KevinZonda** [comment]
> 可以的，但其实最好手动来
> […](#)
> ---原始邮件--- 发件人: "Kevin"<notifications@github.com&gt; 发送时间: 2020年3月6日(周五) 上午10:05 收件人: "zgq354/typecho-theme-next"<typecho-theme-next@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [zgq354/typecho-theme-next] 能否添加超过多少行就变成阅读全文呢 (#14) 我想要一个类似于原主题一样，超越多少行便自动变成阅读全文那种（不显示完全） 希望作者愿意添加这个功能，谢谢啦！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问怎么手动来呢？

**Comment by zgq354** [comment]
WordPress 和 Typecho 有个套路，文章里面加一个 `<!--more-->` 标签就可以截断

例子：
```
显示在文章列表的部分
<!--more-->
只会在正文显示的部分
```

**Comment by KevinZonda** [comment]
> <

好的好的！ 感谢！
