### ISSUE TITLE
请求了不存在的/dist/css/typecho.css

### ISSUE THREAD

**Issue by lapherder** [zgq354/typecho-theme-next#18]
启用主题后，打开网页报错：
GET https://xx.xx/usr/themes/typecho-theme-next/dist/css/typecho.css?v=1 net::ERR_ABORTED 404
GET https://xx.xx/usr/themes/typecho-theme-next/dist/css/main.css?v=1 net::ERR_ABORTED 404
溯源是到header.php中的
\<link rel="stylesheet" type="text/css" href="<?php $this->options->themeUrl('/dist/css/main.css?v=1'); ?>" />
\<link rel="stylesheet" type="text/css" href="<?php $this->options->themeUrl('/dist/css/typecho.css?v=1'); ?>" />
但我在目录中没有看到dist这个文件夹
是哪里最近修改过吗

**Comment by zgq354** [comment]
是的，最近在抽空重构（~~咕咕了5年~~），还没搞完，我直接在master上改了，不好意思= =

可以先基于2021年之前的版本来搞：
在这个 commit 下 download zip 就可以下载到原来的版本了~
https://github.com/zgq354/typecho-theme-next/tree/651c2a105be2e1e23b33335524f0e406970d2ce7
