### ISSUE TITLE
'typecho.css' 404 not found

### ISSUE THREAD

**Issue by chaochao3321** [zgq354/typecho-theme-next#19]
作者您好，我的博客在加载您的主题的时候，提示typechoc.css文件not found，请问一下是这部分内容还没有开发完成吗

**Comment by CornWorld** [comment]
我也遇到了类似问题
发现他缺失了一个 `dist` 文件夹

寻找发现
在 https://github.com/newraina/typecho-theme-NexTPisces 有这个`dist`文件夹

手动进行缝合就好了 )

**Comment by CornWorld** [comment]
emm 但是我发现他的文章页面还是有问题

个人猜测容器的名称不对了

**Comment by zgq354** [comment]
> 作者您好，我的博客在加载您的主题的时候，提示typechoc.css文件not found，请问一下是这部分内容还没有开发完成吗

是的，还没写完，刚把主分支切回了原来的版本，现在重新下载下应该能用了


> 我也遇到了类似问题
> 发现他缺失了一个 `dist` 文件夹
> 
> 寻找发现
> 在 https://github.com/newraina/typecho-theme-NexTPisces 有这个`dist`文件夹
> 
> 手动进行缝合就好了 )

这个 dist 文件夹是构建工具输出的，缝合的话对应的样式不一样所以会有问题
