### ISSUE TITLE
[Bug] 返回顶部按钮的问题

### ISSUE THREAD

**Issue by Darkyyx** [zgq354/typecho-theme-next#3]
按n次返回顶部的按钮，在往下拉，要拉n-1次才能把页面往下拉。
建议在页首的时候直接隐藏图标。

**Comment by zgq354** [comment]
似乎并没有发现这个问题，是在什么浏览器出现的呢

**Comment by Darkyyx** [comment]
Chrome、Firefox、IE 全都是这样的

**Comment by zgq354** [comment]
应该是返回顶部的时候有一段时间是js控制滚动上滑的，然后等这一段时间过去了就正常了，并不是n-1次
